bf2fc6cc711aee1a0c2a/cos-fleetshard

cos-fleetshard-operator-camel-it/src/test/resources/CamelConnectorReify.feature
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandController.java
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandSupport.java
etc/kubernetes/sync/base/kubernetes.yml

- feat: report liveness DOWN when the supervise controller fails all the attemps to restart a route
- feat: set camel man configuration propertiss with secret

Improve camel main configuration set-up

---

cos-fleetshard-operator-camel-it/src/test/java/org/bf2/cos/fleetshard/operator/it/camel/glues/CamelConnectorSteps.java
cos-fleetshard-operator-camel-it/src/test/resources/CamelConnectorReifyErrorHandler.feature
cos-fleetshard-operator-camel-it/src/test/resources/CamelConnectorReifyWithAnnotations.feature
cos-fleetshard-operator-camel/pom.xml
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandController.java
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandSupport.java
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/model/CamelShardMetadata.java
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/model/EndpointKamelet.java
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/model/KameletEndpoint.java
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/model/Kamelets.java
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/model/ProcessorKamelet.java
cos-fleetshard-operator-camel/src/test/groovy/org/bf2/cos/fleetshard/operator/camel/ReifyTest.groovy
cos-fleetshard-operator-camel/src/test/groovy/org/bf2/cos/fleetshard/operator/camel/Spec.groovy
cos-fleetshard-operator-camel/src/test/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandControllerTest.java
cos-fleetshard-operator-debezium/pom.xml
cos-fleetshard-support/src/main/java/org/bf2/cos/fleetshard/support/resources/Secrets.java
etc/kubernetes/connectors/camel/kustomization.yaml
pom.xml

refactor the camel fleet shard operator according to the Public APIs
EPIC Brief

MGDSTRM-6086: refactor the camel fleet shard operator

---

.github/dependabot.yml
pom.xml

- chore: fix the versions-maven-plugin version
- chore: enable dependabot

dependencies

---

cos-fleetshard-operator/src/main/java/org/bf2/cos/fleetshard/operator/connector/ConnectorController.java
cos-fleetshard-operator/src/main/java/org/bf2/cos/fleetshard/operator/connector/ConnectorOperatorEventSource.java
etc/kubernetes/operator-camel/rhoc-staging/app-config/application.properties
etc/kubernetes/operator-camel/rhoc-staging/kustomization.yaml
etc/kubernetes/operator-debezium/rhoc-staging/app-config/application.properties
etc/kubernetes/operator-debezium/rhoc-staging/kustomization.yaml
etc/kubernetes/sync/rhoc-staging/app-config/application.properties
etc/kubernetes/sync/rhoc-staging/app-secret/application.properties
etc/kubernetes/sync/rhoc-staging/kustomization.yaml

- feat: add rhoc-staging kustomizations
- fix: lookup connectors in the right namespace

Add set up for staging data plane and fix connectors lookup

---

README.adoc
cos-fleetshard-operator-camel-it/src/test/java/org/bf2/cos/fleetshard/operator/it/camel/glues/KameletBindingSteps.java
cos-fleetshard-operator-camel-it/src/test/resources/CamelConnectorReify.feature
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandController.java
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/model/KameletEndpoint.java
cos-fleetshard-operator-camel/src/test/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandControllerTest.java
etc/scripts/deploy_camel-k_crds.sh
etc/scripts/deploy_strimzi_crds.sh

This allow kamelets to access the connectors and deployment id if needed

feat(camel): include connector and deployemnt id in KameletBinding

---

cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandController.java
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandSupport.java
cos-fleetshard-operator-camel/src/test/groovy/org/bf2/cos/fleetshard/operator/camel/ReifyTest.groovy
cos-fleetshard-operator-camel/src/test/groovy/org/bf2/cos/fleetshard/operator/camel/Spec.groovy

- feat(camel): leverage schema registry informations from the deployment
- feat(camel): use custom byte serializer

Use schema registry from deployment definition

---

cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifyAvro.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifyJsonWithSchema.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifySchemalessJson.feature
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumConstants.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandController.java
cos-fleetshard-operator-debezium/src/test/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandControllerTest.java

https://issues.redhat.com/browse/MGDCTRS-546

MGCTRS-546 Adding pull secret to Kafka Connect pods

---

cos-fleetshard-operator-camel/src/main/kubernetes/kubernetes.yml
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifyAvro.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifyJsonWithSchema.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifySchemalessJson.feature
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumConstants.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandController.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/model/DebeziumDataShape.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/model/KeyAndValueConverters.java
cos-fleetshard-operator-debezium/src/main/kubernetes/kubernetes.yml
cos-fleetshard-sync/src/main/kubernetes/kubernetes.yml
etc/kubernetes/operator-camel/base/kubernetes.yml
etc/kubernetes/operator-debezium/base/kubernetes.yml
etc/kubernetes/sync/base/kubernetes.yml
etc/scripts/create_pull_secret.sh

* cos-pull-secret renamed to addon-pullsecret
* fix NPE when data_shape is not set
* stop CrashBackLoops for Debezium by setting restartPolicy for Strimzi Kafka Connect pods to Never
closes https://issues.redhat.com/browse/MGDCTRS-602

MGDCTRS-602 Bugfixes: pull secret renaming, NPE when data_shape is not set, Strimzi CrashBackLoops

---

cos-fleetshard-operator-debezium/README.adoc
etc/kubernetes/operator-debezium/lgarciaac/kustomization.yaml
etc/kubernetes/operator-debezium/local/kustomization.yaml
etc/kubernetes/operator-debezium/rh-fuse/kustomization.yaml
etc/kubernetes/operator-debezium/rhoc-staging/kustomization.yaml

https://issues.redhat.com/browse/MGDCTRS-332

MGDCTRS-332 Apply Strimzi selector to Debezium CRs

---

cos-fleetshard-operator-camel/pom.xml
cos-fleetshard-operator-debezium-it/src/test/java/org/bf2/cos/fleetshard/operator/it/debezium/glues/KafkaConnectSteps.java
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifyAvro.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifyJsonWithSchema.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifySchemalessJson.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifyWithExternalConfig.feature
cos-fleetshard-operator-debezium/pom.xml
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandController.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandSupport.java
cos-fleetshard-operator-debezium/src/main/resources/kafka_connect_metrics.yml
cos-fleetshard-operator-debezium/src/test/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandControllerTest.java
pom.xml

closes https://issues.redhat.com/browse/MGDCTRS-600

MGDCTRS-617 Enable and add Prometheus metrics for Debezium connectors

---

etc/kubernetes/operator-camel/local/kustomization.yaml
etc/kubernetes/operator-camel/rh-fuse/kustomization.yaml
etc/kubernetes/operator-camel/rhoc-staging/kustomization.yaml
etc/kubernetes/operator-debezium/local/kustomization.yaml
etc/kubernetes/operator-debezium/rh-fuse/kustomization.yaml
etc/kubernetes/operator-debezium/rhoc-staging/kustomization.yaml
etc/kubernetes/sync/local/kustomization.yaml
etc/kubernetes/sync/rh-fuse/kustomization.yaml
etc/kubernetes/sync/rhoc-staging/kustomization.yaml

I need to be like in stage, where container name match the operator name

Container name should match operator name

---

cos-fleetshard-operator-camel-it/src/test/resources/CamelConnectorReify.feature
cos-fleetshard-operator-camel-it/src/test/resources/CamelConnectorReifyWithAnnotations.feature
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelConstants.java
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandController.java

Hi Luca,
This is the PR for MGDCTRS-349.the 
Though, I still want to check with you on a better way to handle the configuration which I've introduced on the CamelOperandController.java file.
Let's discuss this whenever you are free!
-Shivam

Configuring label selection in camel operator

---

cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorLifecycleStop.feature
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandController.java

closes https://issues.redhat.com/browse/MGDCTRS-712

MGDCTRS-712 Stopping a Debezium connector should not pause the connector but free the resources by deleting them

---

cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandController.java
cos-fleetshard-operator-debezium/src/main/resources/kafka_connect_metrics.yml

closes https://issues.redhat.com/browse/MGDCTRS-727

MGDCTRS-727 Fix metrics config to be a UTF-8 String not a raw byte array

---

.github/workflows/build-main.yaml
.github/workflows/build-tag.yaml
README.adoc
cos-fleetshard-poms/app/pom.xml
etc/scripts/build_image.sh

- ci: configure image tags from github ref
- chore: fix readme

configure image tags from github ref

---

cos-fleetshard-sync-it/src/main/resources/application.properties
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/ConnectorProvisionerTest.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerTest.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerTestBase.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerWithCustomAddonPullSecretNameTest.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerWithCustomPrefixTest.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/support/TestFleetShardSync.java
cos-fleetshard-sync/pom.xml
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/FleetShardSyncConfig.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/resources/ConnectorNamespaceProvisioner.java
cos-fleetshard-sync/src/main/resources/application.properties
etc/kubernetes/manifests/base/apps/cos-fleetshard-operator-camel/app-config/application.properties
etc/kubernetes/manifests/base/apps/cos-fleetshard-operator-debezium/app-config/application.properties
etc/kubernetes/manifests/base/apps/cos-fleetshard-sync/app-config/application.properties
etc/kubernetes/manifests/overlays/bundles/cos-fleetshard-sync/app-config/application.properties

closes https://issues.redhat.com/browse/MGDCTRS-726

MGDCTRS-726 Copy `addon-pullsecret` from operator namespace to tenant namespaces

---

cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifyJsonWithSchema.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifySchemalessJson.feature
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/model/DebeziumDataShape.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/model/KafkaConnectJsonWithSchemaConverter.java
cos-fleetshard-operator-debezium/src/test/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandControllerTest.java

closes https://issues.redhat.com/browse/MGDCTRS-794

MGDCTRS-794 Use Kafka Connect JsonConverter with `schemas.enable=true` for data_shape "JSON with schema"

---

.github/workflows/build-it.yaml
.github/workflows/build-pr.yaml
cos-fleetshard-operator-camel-it/pom.xml
cos-fleetshard-operator-debezium-it/pom.xml
cos-fleetshard-operator-it/pom.xml
cos-fleetshard-sync-it/pom.xml
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerTest.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerTestBase.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/client/FleetShardClient.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/resources/ConnectorNamespaceProvisioner.java
cos-fleetshard-sync/src/test/java/org/bf2/cos/fleetshard/sync/connector/ConnectorTestSupport.java
cos-fleetshard-sync/src/test/java/org/bf2/cos/fleetshard/sync/connector/NamespaceProvisionerTest.java

- MGDCTRS-823: Sanitize names before applying resources
- feat: parallel it

Sanitize names before applying resources

---

cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandController.java

* make topic auto-creation explicitly defined instead of implicitly derived
closes https://issues.redhat.com/browse/MGDCTRS-232

MGDCTRS-232 Add resource quotas (requests and limits) to Debezium Kafka Connect pods

---

cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorEvents.feature
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandController.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandSupport.java
cos-fleetshard-operator-debezium/src/test/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandControllerTest.java

closes https://issues.redhat.com/browse/MGDCTRS-802

MGDCTRS-802 Map `TimeoutException` condition-reason to "The configured Kafka Cluster is unreachable." as error message

---

.github/workflows/build-it.yaml
cos-fleet-manager-api/src/openapi/specs/connector_mgmt-private.yaml
cos-fleet-manager-api/src/openapi/specs/connector_mgmt.yaml
cos-fleet-manager-api/src/openapi/specs/kas-fleet-manager.yaml
cos-fleetshard-operator-camel-it/pom.xml
cos-fleetshard-operator-debezium-it/pom.xml
cos-fleetshard-operator-it/pom.xml
cos-fleetshard-support/src/main/java/org/bf2/cos/fleetshard/support/resources/Resources.java
cos-fleetshard-sync-it/pom.xml
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/ConnectorStatusUpdaterTest.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerBadIdTestBase.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerTestBase.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerWithNoQuotaTestBase.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerWithQuotaDisabledTest.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerWithQuotaEmptyTest.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerWithQuotaNullTest.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/NamespaceProvisionerWithQuotaTest.java
cos-fleetshard-sync-it/src/test/java/org/bf2/cos/fleetshard/sync/it/support/SyncTestSupport.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/FleetShardSyncConfig.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/client/FleetManagerClient.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/client/FleetManagerClientApi.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/resources/ConnectorNamespaceProvisioner.java
cos-fleetshard-sync/src/main/kubernetes/kubernetes.yml
cos-fleetshard-sync/src/test/java/org/bf2/cos/fleetshard/sync/connector/ConnectorTestSupport.java
etc/kubernetes/manifests/base/apps/cos-fleetshard-sync/kubernetes.yml

- MGDCTRS-828: set resource quota assigned to a kubernetes namspace
- MGDCTRS-827: update the status of namespaces when there is a failure creating the resource on kubernetes

Suport namespace quota and status reporting

---

etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/app-config/application.properties
etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/kustomization.yaml
etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/app-config/application.properties
etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/kustomization.yaml
etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/app-config/application.properties
etc/kubernetes/manifests/overlays/staging/cos-fleetshard-sync/kustomization.yaml
etc/kubernetes/manifests/overlays/staging/strimzi/kustomization.yaml

- Changed Configmaps to new log levels.
- Removed `view` Roles from staging kustomize.
- Removed strimzi ClusterRoleBinding from staging kustomize.
- added https://github.com/bf2fc6cc711aee1a0c2a/cos-fleetshard/pull/368 changes to avoid conflicts

fix: kustomize for bundle generation

---

cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandSupport.java
cos-fleetshard-operator-debezium/src/test/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandControllerTest.java

closes https://issues.redhat.com/browse/MGDCTRS-923

MGDCTRS-923 Proper "Ready" condition mapping for KafkaConnect and KafkaConnector custom resources

---

cos-build-tools/src/main/resources/pmd-rules.xml
pom.xml

- chore: run git-commit-id-maven-plugin only once
- chore: replace pmd depprecated rules with the recommended ones

Replace pmd depprecated rules with the recommended ones and run git plugin only once

---

cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumConstants.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandConfiguration.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandController.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/model/AbstractApicurioConverter.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/model/KafkaConnectConverter.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/model/KafkaConnectJsonConverter.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/model/KafkaConnectJsonWithSchemaConverter.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/model/KeyAndValueConverters.java
cos-fleetshard-operator-debezium/src/test/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandControllerTest.java
etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-debezium/app-config/application.properties

https://issues.redhat.com/browse/MGDCTRS-584

MGDCTRS-584 Make apicurio.auth.service.url and apicurio.auth.realm configurable via ConfigMap

---

cos-fleetshard-it/cucumber/src/main/java/org/bf2/cos/fleetshard/it/cucumber/ConnectorSteps.java
cos-fleetshard-operator-debezium-it/src/test/java/org/bf2/cos/fleetshard/operator/it/debezium/DebeziumConnectorEventsWithFailedTaskTest.java
cos-fleetshard-operator-debezium-it/src/test/java/org/bf2/cos/fleetshard/operator/it/debezium/glues/DebeziumConnectorSteps.java
cos-fleetshard-operator-debezium-it/src/test/java/org/bf2/cos/fleetshard/operator/it/debezium/glues/KafkaConnectSteps.java
cos-fleetshard-operator-debezium-it/src/test/java/org/bf2/cos/fleetshard/operator/it/debezium/glues/KafkaConnectorSteps.java
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorEvents.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorEventsWithFailedTask.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorLifecycleDelete.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorLifecycleStop.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorMetricsDelete.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorMetricsDeploy.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorMetricsStop.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifyAvro.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifyJsonWithSchema.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifySchemalessJson.feature
cos-fleetshard-operator-debezium-it/src/test/resources/DebeziumConnectorReifyWithExternalConfig.feature
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandSupport.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/model/ConnectorStatus.java
cos-fleetshard-operator-debezium/src/test/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandControllerTest.java

closes https://issues.redhat.com/browse/MGDCTRS-1139

MGDCTRS-1139 Handle DebeziumExceptions that lead to Kafka Connect task errors but not fails the connector

---

cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandSupport.java

Tested with https://github.com/bf2fc6cc711aee1a0c2a/cos-fleet-catalog-camel/pull/373

MGDCTRS-1414: use original message when sending to DLQ

---

cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/resources/ConnectorStatusUpdater.java

Hi @rinaldodev,
Just added a connector type tag.

Adding connector type tag to the connector status metric

---

README.adoc
cos-fleetshard-operator-camel-it/src/test/resources/CamelConnectorReify.feature
cos-fleetshard-operator-camel-it/src/test/resources/CamelConnectorReifyWithDefaults.feature
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandSupport.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/client/AuthTokenSupplier.java
etc/kubernetes/manifests/base/apps/camel-k/kustomization.yaml
etc/kubernetes/manifests/overlays/local/cos-fleetshard-sync/app-config/application.properties

Needs to be merged before https://github.com/bf2fc6cc711aee1a0c2a/cos-fleet-catalog-camel/pull/382
This contains the upgrade to Camel K 1.10 and adjustments to make it work.

MGDCTRS-1098: upgrade camel related versions

---

.github/dependabot.yml
.github/workflows/build-main.yaml
.github/workflows/build-tag.yaml

- chore: enable Dependabot version updates for actions
- chore: ensure XDG_RUNTIME_DIR exists before invoking skopeo

Enable dependabot for actions and ensure XDG_RUNTIME_DIR exists

---

cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandSupport.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/model/ConnectorStatus.java

closes https://issues.redhat.com/browse/MGDCTRS-1566

MGDCTRS-1566 Stop creating new/duplicated conditions in the ManagedConnector resource with every reconciliation run

---

cos-fleetshard-operator-camel/pom.xml
cos-fleetshard-operator-debezium/pom.xml
cos-fleetshard-sync/pom.xml
etc/kubernetes/manifests/base/apps/camel-k/patches/patch-camel-k-deployment.yaml
etc/kubernetes/manifests/base/apps/cos-fleetshard-operator-camel/kubernetes.yml
etc/kubernetes/manifests/base/apps/cos-fleetshard-operator-debezium/kubernetes.yml
etc/kubernetes/manifests/base/apps/cos-fleetshard-sync/kubernetes.yml
etc/kubernetes/manifests/base/apps/strimzi/operator/kustomization.yaml

closes https://issues.redhat.com/browse/MGDCTRS-1214

MGDCTRS-1214 Fix K8s resource requests and limits for infrastructure components (Fleetshard-Sync, Camel Operator, Debezium Operator, Camel-K, Strimzi)

---

cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandSupport.java
cos-fleetshard-operator-debezium/src/test/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandControllerTest.java

relates to https://issues.redhat.com/browse/MGDCTRS-1671

MGDCTRS-1671 Failing connector should not stuck in provision phase when connection to Kafka Cluster is not possible

---

cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/ConditionMessageImprover.java

Comparison looks really bad but I just wrapped the processing in `if (StringUtils.isNotBlank(originalMessage)) {`

MGDCTRS-1698: avoid NPE in message improver

---

README.adoc
etc/kubernetes/manifests/base/apps/camel-k/patches/patch-camel-k-deployment.yaml
etc/kubernetes/manifests/base/apps/strimzi/operator/kustomization.yaml

Hi @valdar, Please review!
I tried building the new addon locally and these changes reflect on the respective csv.yaml.

Enabling Debug logs for Camel K and Strimzi Operator

---

cos-fleetshard-operator-camel-it/src/test/java/org/bf2/cos/fleetshard/operator/it/camel/CamelConnectorReifyTest.java
cos-fleetshard-operator-camel-it/src/test/resources/CamelConnectorMetricsMonitor.feature
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelOperandController.java
cos-fleetshard-operator-camel/src/main/java/org/bf2/cos/fleetshard/operator/camel/CamelProducers.java
cos-fleetshard-operator-camel/src/main/resources/application.properties
cos-fleetshard-operator-debezium-it/src/test/java/org/bf2/cos/fleetshard/operator/it/debezium/DebeziumConnectorReifyTest.java
cos-fleetshard-operator-debezium-it/src/test/java/org/bf2/cos/fleetshard/operator/it/debezium/DebeziumConnectorReifyWithConfigMapTest.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandController.java
cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumProducers.java
cos-fleetshard-operator-it/src/main/resources/application.properties
cos-fleetshard-operator-it/src/test/java/org/bf2/cos/fleetshard/operator/it/support/TestProducers.java
cos-fleetshard-operator/src/main/java/org/bf2/cos/fleetshard/operator/FleetShardOperatorConfig.java
cos-fleetshard-operator/src/main/java/org/bf2/cos/fleetshard/operator/connector/ConnectorController.java
cos-fleetshard-support/src/main/java/org/bf2/cos/fleetshard/support/metrics/MetricsRecorder.java
cos-fleetshard-support/src/main/java/org/bf2/cos/fleetshard/support/metrics/MetricsSupport.java
cos-fleetshard-support/src/main/java/org/bf2/cos/fleetshard/support/metrics/ResourceAwareMetricsRecorder.java

- metrics: remove histograms and percentiles
- metrics: remove unused tags

meters cleanup

---

cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandController.java
cos-fleetshard-operator-debezium/src/test/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandControllerTest.java

https://issues.redhat.com/browse/MGDCTRS-1869

MGDCTRS-1869 Upgrade Debezium Operator to use new storage config options

---

cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/FleetShardSync.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/FleetShardSyncConfig.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/housekeeping/MetricsHousekeeper.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/housekeeping/MetricsHousekeeperJob.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/resources/ConnectorDeploymentProvisioner.java
cos-fleetshard-sync/src/main/java/org/bf2/cos/fleetshard/sync/resources/ConnectorStatusUpdater.java

Added metrics housekeeper job to remove deleted connectors metrics once a day. Note that it only removes the metrics that are 6 hours older.

MGDCTRS-1113: Added Metrics housekeeping

---

tutorial/tutorial.md

https://issues.redhat.com/browse/MGDCTRS-2062

[MGDCTRS-2062] First draft of the tutorial

---

cos-fleetshard-operator-debezium/src/main/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandSupport.java
cos-fleetshard-operator-debezium/src/test/java/org/bf2/cos/fleetshard/operator/debezium/DebeziumOperandControllerTest.java

closes https://issues.redhat.com/browse/MGDCTRS-1737

MGDCTRS-1737 Handle timeout exception properly in case of a failure on initial startup

---

etc/kubernetes/manifests/base/apps/camel-k/patches/patch-camel-k-deployment.yaml
etc/kubernetes/manifests/base/apps/cos-fleetshard-operator-camel/app-config/application.properties
etc/kubernetes/manifests/overlays/dev/camel-k/integration-platform.yaml
etc/kubernetes/manifests/overlays/e2e/kustomization.yaml
etc/kubernetes/manifests/overlays/local/camel-k/integration-platform.yaml
etc/kubernetes/manifests/overlays/staging/camel-k/integration-platform.yaml
etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/app-config/application.properties

This PR is against https://issues.redhat.com/browse/MGDCTRS-1745, where we are basically enabling the Label Selection feature.

MGDCTRS-1745: Enabling Label Selection feature in Camel-K
